murabahah_rules = """
1.	Scope of the Standard
       This standard covers the Murabahah transaction and its various stages, the issues relating to guarantees before concluding a Murabahah deal such as promise, Hamish Jiddiyyah (security deposit) and issues relating to guarantees for recovery of the debt created by the Murabahah transaction.
       This standard does not cover deferred payment sales that take place on a basis other than that of Murabahah. It also does not cover other trust and bargaining sales.
2.	Procedures Prior to the Contract of Murabahah
   2/1 The customer’s expression of his wish to acquire an item through the Institution
       2/1/1 The Institution may purchase the item only in response to its customer’s wish and application, as long as this practice is compatible with the Shari’ah precepts for the contract of sale.
       2/1/2 With due consideration to item 2/2/3, it is permissible for the customer to request the Institution to purchase the item from a particular source of supply. However, the Institution is entitled to decline to carry out the transaction if the customer refuses offers from other sources of supply that are more suitable for the Institution.
       2/1/3 The customer’s wish to acquire the item does not constitute a promise or commitment except when it has been expressed in due form. It is permissible to prepare a single set of documentation to be signed by the customer and to include both the customer’s stated wish that the Institution should buy the item from the supplier and a promise to buy the item from the Institution. It is permissible for the customer to prepare such a document, or it may be a standard application form prepared by the Institution to be signed by the customer.
       2/1/4 The customer may obtain statement of prices from the supplier whether they are addressed to the customer by name [specific offer], or with no reference to any named customer [general offer]. In the latter case, the statement is considered as an invitation to negotiate, and not as an offer of sale. It is preferable that the invoice should be addressed to the Institution so as to include an offer of sale from the supplier effective up to the end of a specified period. The contract of sale is deemed concluded once acceptance comes from the Institution.
   2/2 The position of the Institution in respect to the application of the customer for Murabahah
       2/2/1 When there is acceptance by the customer of an offer from the supplier that is either addressed to him personally, or that has no addressee, then the sale is concluded with the customer and so it is not permissible for the Institution to carry out Murabahah on the same item.
       2/2/2 It is essential to exclude any prior contractual relationship between the customer who is the purchase orderer and the original supplier of the item ordered, if any, regarding the supply of the item. It is a requirement of Murabahah that the transaction between the two parties must genuinely, not fictitiously, exclude any prior contractual relationship. It is not permissible to assign a contract that has been executed between the customer and the supplier of the ordered item to the Institution.
       2/2/3 The Institution must ensure that the party from whom the item is bought is a third party other than customer or his agent. For example, it is not permitted for a customer to sell an ordered item to the Institution and then repurchase it through a Murabahah transaction. Nor may the party that is supplying the item be wholly, or by way of majority [more than 50%], owned by the customer. If a sale transaction takes place and later on it is discovered that it was carried out through such practices, this would render the transaction void as it is tantamount to ’Inah.
       2/2/4 If the supplier (owner) of the item has a blood relationship or marital relationship with the customer, then the Institution shall verify, before entering into Murabahah, that the sale is not fictitious and not a stratagem for the sale of ’Inah.
       2/2/5 It is not permissible for the Institution and the customer to agree to form a Musharakah in a project or a specified deal together with a promise from one of them to buy the other’s share in Musharakah by means of Murabahah on either spot or deferred payment terms. However, it is permissible for one partner to promise to purchase the other’s share in Musharakah at market price or at a price to be agreed upon at the time of sale provided a new contract is drawn up. This sale may be on spot or on deferred payment terms.
       2/2/6 It is not permitted to carry out a Murabahah on deferred payment terms where the asset involved is gold, silver or currencies.
       2/2/7 It is also impermissible to issue negotiable Sukuk where the underlying asset consists of Murabahah receivables or other receivables only.
       2/2/8 Likewise, it is not permitted to renew a Murabahah contract on the same commodity that was the subject matter of a previous Murabahah contract with the same customer, i.e. to refinance the transaction.
   2/3 The promise from the customer
       2/3/1 It is not permissible that the document of promise to purchase (signed by the customer) should include a bilateral promise which is binding on both parties (the Institution and the customer).
       2/3/2 The customer’s promise to purchase, and the related contractual framework, are not integral to a Murabahah transaction, but are intended to provide assurance that the customer will complete the transaction after the item has been acquired by the Institution. If the Institution has other opportunities to sell the item, then it may not need such a promise or contractual framework.
       2/3/3 A bilateral promise between the customer and the Institution is permissible only if there is an option to cancel the promise which may be exercised either by both promisors or by either one of them.
       2/3/4 It is permissible for the Institution and the customer, after the latter has given a promise but before the execution of the Murabahah, to agree to revise the terms of the promise whether with respect to the deferment of payment, the markup or other terms. The terms of the promise cannot be revised except by mutual consent by both parties.
       2/3/5 It is permissible for the Institution to purchase the item from a supplier on a “sale or return” basis, i.e., with the option to return it within a specified period. If the customer then does not purchase the item, the Institution is able to return it to the supplier within the specified period on the basis of the conditional option that is established in Shari’ah. The option between the Institution and the supplier does not expire by the mere presentation of the item to the customer, but it expires by virtue of the actual sale to the customer. It is advisable to stipulate in a stipulated option to revoke (khiyar alShart) that the mere offer by the purchaser for the sale of the item to a third party does not invalidate the option.
   2/4 Commissions and expenses
       2/4/1 It is not permissible for the Institution to receive a commitment fee from the customer.
       2/4/2 It is not permissible for the Institution to receive a fee for providing a credit facility.
       2/4/3 The expenses of preparing the documents of the contract between the Institutions and the customer are to be borne evenly by the two parties (the Institution and the customer), provided they do not agree that the expenses are to be borne wholly by one party, and provided those expenses are proportional to the actual amount of work involved, so that they do not implicitly include a commitment fee or a facility fee.
       2/4/4 If the Murabahah is carried out by means of syndicated financing, the Institution which acts as the arranger of the syndicate is entitled to an arrangement fee to be paid by the participants in the syndicate.
       2/4/5 It is permissible for the Institution to receive a fee for a feasibility study that it undertakes in case such study is requested by the customer and for the benefit thereof and the customer agrees to pay the fee thereof. The customer is entitled to a copy of the study if he so requires.
   2/5 Guarantees related to the commencement of the transaction
       2/5/1 It is permissible for the Institution to obtain from the customer (the purchase orderer) a guarantee (performance deed) regarding the good performance by the supplier of his contractual obligations towards the Institution in his personal capacity and not in his capacity as purchase orderer or in his capacity as an agent of the Institution. Hence, if the Murabahah contract is not executed, his guarantee would still be valid. This guarantee is required only in cases where the customer has suggested a particular source of supply for the item that is the subject matter of the Murabahah contract. As a consequence of this guarantee, the customer shall make good any damage suffered by the Institution due to failure of the supplier to provide good performance of his contractual obligations. These obligations concern meeting the specification of the item to be supplied and the exercise of diligence in executing the contract, non-observance of which may result in the loss of the Institution’s time and efforts or property, or in a legal dispute and damage claims.
       2/5/2 It is not permitted to impose on a customer who is the purchase orderer a guarantee regarding hazards that may affect the item such as damage and destruction during a period of shipment or storage.
       2/5/3 It is permissible for the Institution, in the case of a binding promise by the customer, to take a sum of money as Hamish Jiddiyyah (security deposit). This is to be paid by the customer at the request of the Institution, both as an indication of the financial capacity of the customer and to ensure the compensation of any damage to the Institution arising from a breach by the customer of his binding promise. Having taken this Hamish Jiddiyyah, the Institution need not to demand compensation for damage as this may be charged against the Hamish Jiddiyyah. The Hamish Jiddiyyah is not considered as ’Arboun (Earnest Money). The amount of money deposited by the customer as security for his commitment can be either held, if the customer permits the Institution to invest it, as an investment trust on the basis of Mudarabah between the customer and the Institution, or held in a current account at the discretion of the customer.
       2/5/4 In the case of the customer’s breach of his binding promise, the Institution is not permitted to retain Hamish Jiddiyyah as such. Instead, the Institution’s rights are limited to deducting the amount of the actual damage incurred as a result of the breach, namely the difference between the cost of the item borne the Institution and the price at which the item is sold to a third party. The actual damage to the Institution may not include the loss of its mark-up in the Murabahah transaction, that is, its opportunity loss.
       2/5/5 When the customer has fulfilled his promise and executed the contract of Murabahah, the Institution must refund Hamish Jiddiyyah to the customer. The Institution is not entitled to receive any amount out of Hamish Jiddiyyah except in the case of breach of promise as laid down in item 2/5/3. It is permissible for the Institution to agree with the customer that the amount of Hamish Jiddiyyah will be deducted from the price payable by the customer pursuant to the contract of Murabahah.
       2/5/6 It is permissible for the Institution to take ’Arboun (Earnest Money) upon conclusion of the Murabahah sale with the customer. This may not be done during the contractual stage at which the customer has given his promise to purchase. In the event that the customer revokes the contract in an ’Arboun-based transaction, it is preferable that the Institution, after deducting the actual damage it incurs, refunds the remaining amount of ’Arboun to the customer. The damage in this context means the difference between the cost of the item borne the Institution and the price at which the item is sold to a third party.
3.	Acquisition of Title to, and Possession of, the Asset by the Institution or Its Agent 
   3/1 The acquisition of the asset or good by the Institution prior to its sale by means of Murabahah
       3/1/1 The Institution shall not sell any item in a Murabahah transaction before it acquires such item. Hence, it is not valid for the Institution to conclude a Murabahah sale with the customer before the Institution concludes a urchase contract with the supplier of the item the subject matter of the Murabahah and before it acquires actual or constructive possession of such items, which can be achieved when the supplier gives the Institution control over the item or the documents that represent possession thereof [see items 3/2/1-3/2/4]. Likewise, the Murabahah is considered void in case the contract with the supplier is void, because 
       in this case the Institution would fail to acquire complete title to the item.
       3/1/2 It is permitted that the contract between the Institution and the supplier be completed by means of a meeting of the two parties to discuss the details, at which point the contract may be executed. Likewise, it is permitted that the contract be completed through exchanging of the notices of offer and acceptance, either in writing or by any form of modern communication customarily practiced according to known principles.
       3/1/3 The original principle is that the Institution itself purchases the item directly from the supplier. However, it is permissible for the Institution to carry out the purchase by authorizing an agent, other than the purchase orderer, to execute the purchase; and the customer (the purchase orderer) should not be appointed to act as an agent except in case of a dire need. Furthermore, the agent must not sell the item to himself. Rather, the Institution must first acquire title of the item and then sell it to the agent. In such a case, the provisions of item 3/1/5 should be observed.
       3/1/4 In cases when the customer is authorized to purchase the item as the Institution’s agent, it is obligatory to adopt procedures which would ensure that certain conditions are observed. These conditions include:
              a) the Institution itself must pay the supplier, and not pay the price of the item into the account of the customer as agent, whenever possible.
              b) the Institution should obtain from the supplier the documents that confirm that a sale has taken place.
       3/1/5 It is obligatory to separate the two liabilities of risk attaching to the purchased item, namely the liability of the Institution and the liability of the customer as agent of the Institution. This is achieved by having an interval in time between the performance of the agency contract and the execution of the contract of Murabahah, as indicated in the customer’s notice of performance of the agency contract to acquire the item and offer to purchase the item by means of Murabahah [see Appendix (a)], followed by the institution’s notice of its acceptance of the customer’s offer to purchase and the execution of the Murabahah sale contract [see Appendix (b)].
       3/1/6 The original principle is that all documents and contracts concerned with the execution of the sale of the item must be in the name of the Institution and not in that of the customer, unless the latter acts as the Institution’s agent in acquiring the item.
       3/1/7 It is permissible, at the time when the Institution appoints someone as its agent for the acquisition of the item, that the two parties agree to authorize the agent to carry out the acquisition of the item as agent, without disclosing the existence of the agency agreement. In this case, the agent will act as principal in dealing with other parties, and will undertake the purchase directly in his name but on behalf of the Institution as principal. However, it is preferable that the agent’s role be disclosed.
   3/2 The Institution’s taking possession of the asset or good, prior to its sale by Murabahah
       3/2/1 It is obligatory that the Institution’s actual or constructive possession of the item be ascertained before its sale to the customer on the basis of Murabahah.
       3/2/2 The condition that possession of the item must be taken by the Institution (before its onward sale to the customer) has a specific purpose: that the Institution must assume the risk of the item it intends to sell. This means that the item must move from the responsibility of the supplier to the responsibility of the Institution. Similarly, it is obligatory that the point when the risk of the item is passed on by the Institution to the customer be clearly identified, with reference to the stages in which the item is transferred from one party to another.
       3/2/3 The forms of taking delivery or possession of items differ according to their nature and different trade customs. Taking possession may be actual in the case of the physical delivery or transportation to the acquirer or its agent, but may also take place constructively by placing of the item at the acquirer’s disposal so as to enable him to deal with it at his will, even though no physical delivery has taken place. Taking possession of an item of real property may also take place by means of the property being vacated and its being placed at the acquirer’s disposal; if the latter is not able to have disposal of the purchased item, then the vacation of the property is not considered as conveying possession. In the case of moveable assets, possession will take place in accordance with the nature of the asset.
       3/2/4 The receipt of a bill of lading by the Institution or its agent, when purchasing goods on the international market, is considered as constructive possession. The same would apply to the Institution’s receipt of certificates of storage issued by warehouses following appropriate and reliable formalities.
       3/2/5 The original principle is that the Institution itself must receive the item from the premises of the supplier or from a location that is specified in the delivery conditions. The responsibility for the risk attached to the item is transferred to the Institution upon its taking possession of the item. However, it is permissible for the Institution to authorize another party to take delivery of the item on its behalf.
       3/2/6 As the Institution is the owner of the subject matter of Murabahah its insurance lies with the Institution before selling it to the customer. Any amount recovered from insurance at this stage will belong to the Institution exclusively and the customer has no claim to it even if the recovered amount exceeds the purchase price. The Institution is entitled to include the expenses of insurance in the Murabahah cost price to be subsequently added to the price of Murabahah. Insurance must be on the basis of Takaful whenever possible.
       3/2/7 Agency in carrying out the procedures of obtaining insurance cover for the item at the stage of the Institution’s acquisition of ownership of the asset is permitted. However, it is obligatory that the Institution should bear the cost of insurance.
4.	Conclusion of a Murabahah Contract
   4/1 It is not permitted for the Institution to consider that the contract of Murabahah is automatically concluded by its mere taking possession of the asset. Likewise, the Institution may not force a customer who is the purchase orderer to take delivery of the asset and pay the Murabahah selling price, if the customer refuses to conclude the Murabahah transaction.
   4/2 The Institution is entitled to receive compensation for any actual damage it has incurred as a result of the customer’s breach of a binding promise. The compensation consists of the customer reimbursing the Institution for any loss due to a difference between the price received by the Institution in selling the asset to a third party and the original cost price paid by the Institution to the supplier.
   4/3 When the Institution has purchased an asset for a deferred price, with the intention that it will be sold on a Murabahah basis, then the Institution is obliged to disclose to the customer that the asset is purchased by the Institution on deferred payment basis. The Institution has the obligation to disclose to the customer, when concluding the contract of sale, the details of any expenses that it would include in determining the cost. The Institution is also entitled to include any expenses relating to the item if this is acceptable to the customer. However, if the Institution failed to disclose any expenses, it is not entitled to include them unless they are customarily considered as normal expenses, such as transportation expenses, storage expenses, fees for letters of credit and insurance premiums.
   4/4 The Institution is not entitled to include in the base cost of the item, for the purpose of calculating the Murabahah price, any amounts other than the direct expenses that are paid to a third party. It is not permissible, for example, for the Institution to add to the cost of the item payments made to its own staff for their work, and the like.
   4/5 If the Institution has, even after the drawing up of the Murabahah contract, received a discount for the same item that was sold on Murabahah basis from the supplier of the item, then the customer should benefit from that discount by a reduction of the total Murabahah selling price in proportion to the discount.
   4/6 It is an obligation that both the price of the item and the Institution’s profit on the Murabahah transaction be fixed and known to both parties on the signature of the contract of sale. It is not permitted under any circumstances to subject the determination of the price or the profit to unknown variations or variations that are determinable in the future, such as by concluding the sale and making the profit dependent on the rate of LIBOR that will prevail in the future. There is no objection to referring to any other known indicators during the promise stage as a comfort indicator to determine the rate of profit, provided that the determination of the Institution’s profit at the time of concluding the Murabahah is based on a certain percentage of the cost and is not tied up with LIBOR or a time factor.
   4/7 The Institution’s profit mark-up in Murabahah must be known, and the mere mention of the total selling price is not sufficient. It is permissible that the profit be determined based on a lump sum amount or a certain percentage of the cost price only or of the cost price plus the expenses. This determination is completed by the agreement and mutual consent of the two parties.
   4/8 It is permissible to agree on the payment of the price of the item under Murabahah either by short or long term instalments, and the selling price of the asset becomes a debt that the customer is obligated to pay at the time agreed upon. It is not permitted subsequently to demand any extra payment either in consideration of extra time given for payment or for delay in payment that may be for a reason or no reason.
   4/9 It is permissible for the Institution to stipulate in the contract of Murabahah a condition that the Institution is free from responsibility for all or some of the defects of the asset, but not from destruction caused before the possession of the customer or diminution of quantity sold; this is known as Bay’ al-Bara`ah (sale on ‘as is’ basis). In the case of stipulating such a condition, it is preferable that the Institution should assign to the customer the right of recourse to the supplier to obtain compensation for any defects that are established, which would otherwise be recoverable by the Institution from the supplier.
   4/10 The Institution shall be responsible for pre-existing hidden defects which appear after the conclusion of the contract, unless it stipulates otherwise according to item 10/4. However, it shall not be responsible for any new defects (recent defects) that arise after the conclusion of the contract and taking delivery by the customer.
   4/11 The Institution is entitled to include, as a condition of the contract, that in case of the customer’s refusal, after the execution of the Murabahah contract, to take delivery of the asset at the prescribed time, the Institution could revoke the contract or sell the asset to a third party on behalf of the customer and for his account. The Institution could then recover from the selling price the amount due to it from the customer under the contract, and would have recourse to the customer for the balance if that price were not sufficient to cover the amount due to the customer.
5.	Guarantees and Treatment of Murabahah Receivables
   5/1 It is permissible for the Institution to stipulate to the customer that installments may become due before their originally agreed due dates in case of the customer’s refusal or delay in paying any instalment without any valid reason after the lapse of the time specified in the notice to be sent by the Institution to the customer within a reasonable period of time following the due date.
   5/2 The Institution should ask the customer to provide permissible security in the contract of Murabahah. Among other things, the Institution may receive a third party guarantee or the mortgagee of the investment account of the customer or the mortgagee of any item of real or moveable property, or the mortgagee of the subject matter of the Murabahah contract as a fiduciary mortgagee (or a registered charge), either without taking possession of the mortgaged asset, or by taking possession of the mortgaged asset and then releasing the mortgagee progressively according to the percentage of the total payment received.
   5/3 It is permissible for the Institution to require the customer to provide cheques or promissory notes before the execution of the contract of Murabahah, as a guarantee of the indebtedness that will be created after the execution of the contract. This is possible on the written condition that the Institution is not entitled to use these cheques or documents except on their due dates. The requirement to provide cheques as security is not permissible in countries where they could be presented for payment before their due date.
   5/4 It is not permissible to stipulate that the ownership of the item will not be transferred to the customer until the full payment of the selling price. However, it is permissible to postpone the registration of the asset in the customer’s name as a guarantee of the full payment of the selling price. The Institution may receive authority from the customer to sell the asset in case the customer delays payment of the selling price, in which case the Institution should issue a countered to the customer to establish the latter’s right to ownership. If the Institution sells the asset as a result of the customer’s failure to make a payment of the selling price on its due date, it must confine itself to recovering the amount due to it and must return the balance to the customer.
   5/5 In the case of the Institution receiving a mortgagee from the customer, the Institution is entitled to stipulate that the customer should make an assignment to the Institution to enable it to sell the mortgaged asset for the purpose of recovering the amount due from the customer without recourse to the judiciary.
   5/6 It is permissible that the contract of Murabahah consists of an undertaking from the customer to pay an amount of money or a percentage of the debt, on the basis of undertaking to donate it in the event of a delay on his part in paying installments on their due date. The Shari’ah Supervisory Board of the Institution must have full knowledge that any such amount is indeed spent on charitable causes, and not for the benefit of the Institution itself.
   5/7 It is not permissible to extend the date of payment of the debt in exchange for an additional payment in case of rescheduling, irrespectively of whether the debtor is solvent or insolvent.
   5/8 When there is default in payment by the customer with regard to installments of the selling price that are due, the amount due is just the amount of the unpaid selling price. It is not permissible for the Institution to impose any additional payment on the customer for the Institution’s benefit. This provision is, however, subject to item 5/6 .
   5/9 It is permissible for the Institution to give up part of the selling price if the customer pays early, provided this was not part of the contractual agreement.
   5/10 If the customer wishes to pay in a currency different from Murabahah currency, it is permissible, with the agreement of the Institution at the time of payment on condition that the payable debt is paid in full or the amount agreed to be paid in different currency is paid in full and no part of the currency exchange amount remains due. This currency exchange may not be stipulated in the contract of Murabahah.
"""

mudarabah_rules = """
1. Scope of the Standard
 This standard covers Mudarabah contracts between the Institution and the other entities or individuals. It also covers joint investment accounts and special purpose investment accounts if these accounts are administered on the basis of Mudarabah.
 The standard does not cover Sukuk of Mudarabah (Mudarabah Certificates) or other types of partnership contracts, as these are covered by separate standards.
2. Definition of Mudarabah
 Mudarabah is a partnership in profit whereby one party provides capital (Rab al-Mal) and the other party provides labour (Mudarib).
3. Agreement of Mudarabah Financing
3/1 It is permissible, on the basis of a general framework or a memorandum of understanding, to conclude Mudarabah financing contracts for a particular sum of money and within a particular defined duration provided that the memorandum of understanding will be later implemented in line with specific or successive Mudarabah transactions.
3/2 The memorandum of understanding should define the general contractual framework, indicating the intention of the parties to use either unrestricted or restricted Mudarabah financing instrument, either through revolving transactions or separate transactions. Also, the memorandum of understanding should indicate the profit ratio, and type of guarantees that shall be presented by the Mudarib to cover situations of negligence, misconduct or breach of contract and other relevant issues in this regard.
3/3 If the Mudarabah contract is actually concluded on the basis of the memorandum of understanding, the contents of the memorandum become an integral part of any future contract, unless the parties had originally agreed to exempt themselves from some of the obligations mentioned therein.
4. Mudarabah Contract
4/1 The Mudarabah contract may be concluded using terms such as Mudarabah, Qirad or Mu'amalah.
4/2 Both parties should possess the legal capacity to appoint agents and accept agency. Therefore, a Mudarabah contract may not be concluded in the absence of two contracting parties with absolute legal capacity or of their agents who enjoy legal capacity similar to that of the contracting parties.
4/3 The general principle is that a Mudarabah contract is not binding, i.e. each of the contracting parties may terminate it unilaterally except in two cases:
4/3/1 When the Mudarib has already commenced the business, in which case the Mudarabah contract becomes binding up to the date of actual or constructive liquidation.
4/3/2 When the contracting parties agree to determine a duration for which the contract will remain in operation. In this case, the contract cannot be terminated prior to the end of the designated duration, except by mutual agreement of the contracting parties.
4/4 A Mudarabah contract is one of the trust-based contracts. Therefore, the Mudarib is investing Mudarabah capital on a trust basis in which case the Mudarib is not liable for losses except in case of breach of the requirements of trust, such as misconduct in respect to the Mudarabah fund, negligence and breach of the terms of Mudarabah contract. In committing any of these, the Mudarib becomes liable for the amount of the Mudarabah capital.
5. Types of Mudarabah
 	Mudarabah contracts are divided into unrestricted and restricted Mudarabah.
5/1 An unrestricted Mudarabah contract is a contract in which the capital provider permits the Mudarib to administer a Mudarabah fund without any restrictions. In this case, the Mudarib has a wide range of trade or business freedom on the basis of trust and the business expertise he has acquired. An example of unrestricted Mudarabah is when the capital provider says, "Do business according to your expertise". However, such unrestricted business freedom in an unrestricted Mudarabah must be exercised only in accordance with the interests of the parties and the objectives of the Mudarabah contract, which is making profit. Therefore, the actions of the Mudarib must be in accordance with the business customs relating to the Mudarabah operations: the subject matter of the contract.
5/2 A restricted Mudarabah contract is a contract in which the capital provider restricts the actions of the Mudarib to a particular location or to a particular type of investment as the capital provider considers appropriate, but not in a manner that would unduly constrain the Mudarib in his operations.
6. Guarantees in a Mudarabah Contract
 The capital provider is permitted to obtain guarantees from the Mudarib that are adequate and enforceable. This is circumscribed by a condition that the capital provider will not enforce these guarantees except in cases of misconduct, negligence or breach of contract on the part of Mudarib. 7. Requirements Relating to the Capital
7/1 In principle, the capital of Mudarabah must be provided in the form of cash. However, it may be presented in the form of tangible assets, in which case the value of the assets is the contribution to the Mudarabah capital. The valuation of the assets may be conducted by experts or as agreed upon by the contracting parties.
7/2 The capital of Mudarabah should be clearly known to the contracting parties and defined in terms of quality and quantity in a manner that eliminates any possibility of uncertainty or ambiguity.
7/3 It is not permissible to use a debt owed by the Mudarib or another party to the capital provider as capital in a Mudarabah contract.
7/4 For a Mudarabah contract to be valid and for the Mudarib to be considered as having control over the capital, the capital must be, wholly or partially, put at the disposal of the Mudarib, or the Mudarib must have free access to the capital.
8. Rulings And Requirements Relating to Profit
8/1 It is a requirement that the mechanism for distributing profit must be clearly known in a manner that eliminates uncertainty and any possibility of dispute. The distribution of profit must be on the basis of an agreed percentage of the profit and not on the basis of a lump sum or a percentage of the capital.
8/2 In principle, it is not permissible to earn a share of profit in addition to a fee in a Mudarabah contract. However, it is permissible for the two parties to construct a separate agreement independent of the Mudarabah contract assigning one party to perform, for a fee, a business activity that is not by custom part of Mudarabah operations. The independence of this separate agreement means that if the contract of providing this activity is terminated, this will not affect the contract of Mudarabah.
8/3 The parties shall agree on the ratio of profit distribution when the contract is concluded. It is also permissible for the parties to change the ratio of distribution of profit at any time and to define the duration for which the agreement will remain valid.
8/4 If the parties did not stipulate the ratio of profit distribution, then they shall refer to customary practice, if any, to determine the shares of profit. If the customary practice is that the profit is distributed equally, then this will be applied as such. If there is no customary practice in this regard, the Mudarabah contract is regarded void 
ab initio, and the party who acts as the Mudarib should receive a common market price for the kind and amount of services that he provided as Mudarib.
8/5 If one of the parties stipulates that he should receive a lump sum of money, the Mudarabah contract shall be void. This rule does not apply to a situation where the parties agree that if the profit is over a particular ceiling then one of the parties will take the additional profit and if the profit is below or equal to the amount of the ceiling the distribution of profit will be in accordance with their agreement.
 8/6 It is not permissible for the capital provider to give the Mudarib two amounts of capitals on condition that the profit earned on one of the two amounts would be taken by the Mudarib while the capital provider would take the profit earned on the other amount. It is not also permissible for the capital provider to state that the profit of one financial period would be taken by the Mudarib and the capital provider would take the profit of the following financial period. Similarly, it is not permissible to assign the profit from a particular transaction to the Mudarib and the profit from another transaction to the capital provider. 
8/7 No profit can be recognised or claimed unless the capital of the Mudarabah is maintained intact. Whenever a Mudarabah operation incurs losses, such losses stand to be compensated by the profits of future operations of the Mudarabah. The losses brought forward should be set against the future profits. All in all, the distribution of profit depends on the final result of the operations at the time of liquidation of the Mudarabah contract. If losses are greater than profits at the time of liquidation, the balance (net loss) must be deducted from the capital. In this case, as he is a trustee the Mudarib is not liable for the amount of this loss, unless there is negligence or misconduct on his part. If the total Mudarabah expenses are equal to the total Mudarabah revenues, the capital provider will receive his capital back without either profit or loss, and there will be no profit in which the Mudarib is entitled to a share. If profit is realised, it must be distributed between the parties as per the agreement.
8/8 The Mudarib is entitled to a share of profit as soon as it is clear that the operations of the Mudarabah have led to the realisation of a profit. However, this entitlement is not absolute, as it is subject to the retention of interim profits for the protection of the capital. It will be an absolute right only after distribution, i.e. when actual or constructive valuations take place. It is permissible to distribute the realised profit among the parties on account, in which case the distribution will be revised when actual or constructive valuation takes place. The final distribution of profit should be made based on the selling price of the Mudarabah assets, which is known as actual valuation. It is also permissible that the profit be distributed on the basis of constructive valuation, which is valuation of the assets on the basis of fair value. Receivables shall be measured at the cash equivalent, or net realisable value, i.e. after the deduction of a provision for doubtful debts. In measuring receivables, neither time value (interest rate) nor discount on current value for extension of period of payment shall be taken into consideration.
8/9 If the Mudarib has commingled his own funds with the Mudarabah funds, the Mudarib becomes a partner in respect of his funds and a Mudarib in respect of the funds of the capital provider. The profit earned on the two commingled funds will be divided proportionately to the amounts of the two funds, in which case the Mudarib takes the profit attributable to his own funds, while the remaining profit is to be distributed between the Mudarib and the capital provider according to the provisions of the Mudarabah contract.
9. Duties and Powers of the Mudarib
 The Mudarib should employ his best efforts to accomplish the objectives of the Mudarabah contract. The Mudarib should assure the capital provider that his money is in good hands that will act to find the best ways of investing it in a permissible manner.
9/1 If a Mudarabah contract is concluded on an unrestricted basis, the Mudarib is permitted, in general, to do what entrepreneurs do in his field of activity, including the following:
9/1/1 Attending to all permissible investment or trading fields that are feasible, given the amount of the capital at his disposal, and in which he believes that his expertise, and technical and professional qualifications are likely to give him the ability to compete effectively.
9/1/2 Carrying out the work himself or appointing another person to carry out some work if necessary, such as buying a commodity or marketing it for him.
9/1/3 Choosing as far as possible appropriate places and markets that are seemingly free of risks.
9/1/4 Safeguarding the Mudarabah funds or depositing them in the custody of a trustworthy person whenever appropriate.
9/1/5 Selling and buying on a deferred payment basis.
9/1/6 The Mudarib may do, either by permission or appointment of the capital provider, the following:
a) The Mudarib may, at any time, combine a Mudarabah contract and a partnership (Sharikah) contract, irrespective of whether this takes place at the outset of the contract or after the commencement of Mudarabah operations, and of whether the partnership contribution is from the Mudarib himself or from a third party. The mixture of unrestricted investment deposits with the Institutions' funds is an example of this kind of combination.
b) The Mudarib may accept funds from a third party ona Mudarabah basis if this new contract will not affect his investment and management responsibility in respect of the first Mudarabah contract.
9/2 It is permissible for the capital provider, on the basis of his interests, to place restrictions on the actions of the Mudarib. Thus, Mudarabah operations may be restricted to a specified time and place, so that the Mudarib may only invest the Mudarabah funds during a particular time period or in a specified country or in a market of a particular country. In addition, the Mudarabah operations may be restricted to investment in certain sectors such as services or trade sectors or a single commodity or a group of commodities. However, restricting the Mudarabah operations to certain commodities is circumscribed with a condition that such commodities must be commonly available so that, other things being equal, the restriction will not prevent the objectives of the Mudarabah contract from being achieved. For example, the commodities to which the Mudarabah is restricted must not be scarce, seasonal (and out of season) or in very limited supply with the consequence that the objectives of the Mudarabah contract cannot be achieved.
9/3 The capital provider is not permitted to stipulate that he has a right to work with the entrepreneur (Mudarib) and to be involved in selling and buying activities, or supplying and ordering. However, the Mudarib should refer to him in performing any action and should not act without consulting him. Also, the capital provider is not entitled to lay down conditions that will restrict movements or actions of the Mudarib, such as a stipulation that the Mudarib must enter into a partnership with others or a stipulation that the Mudarib must mix his personal funds with the Mudarabah funds.
9/4 The Mudarib must carry out all the work that any similar asset or fund manager would be liable, by custom, to do. In this case, the Mudarib is not entitled to a fee for this work as this is part of his responsibilities. If the Mudarib appoints another party on an Ijarah (hiring contract) basis to carry out such work, the wages for the worker must be paid from the personal funds of the Mudarib and not from the Mudarabah funds. The Mudarib may hire against the account of Mudarabah funds another party, at the prevailing rate, to execute work that is not by custom the responsibility of the Mudarib. 
9/5 The Mudarib is not entitled to sell items for the Mudarabah operation at less than the common or market price, or to buy items for the Mudarabah operation at a price higher than common prices, unless if such action in either case is intended to achieve an objective that is obviously in the interest of the Mudarabah. 
9/6 It is not permissible for the Mudarib to make a loan or a gift or a charitable donation out of the Mudarabah funds. Likewise, the Mudarib is not entitled to waive a right associated with the Mudarabah operation unless the capital provider has consented to his doing so.
9/7 If the Mudarib has a right to receive living expenses from the Mudarabah funds that has been approved by the capital provider, then he is entitled to the amount so approved for him. If there is no agreement on this, then the Mudarib should take living expenses in accordance with custom and reason. The Mudarib is also entitled to travelling expenses in accordance with custom and reason.
10. Liquidation of a Mudarabah Contract
10/1 A Mudarabah contract can be liquidated in the following manner:
10/1/1 Being a non-binding contract, it can be liquidated by unilateral termination of the contract by one of the parties. 
[see item 4/3]
10/1/2 With the agreement of both parties.
10/1/3 On the date of maturity if the two parties had earlier agreed to set a time limit for it. [see item 3/4]
10/1/4 When the funds of Mudarabah contract have been exhausted or have suffered losses.
10/1/5 The death of the Mudarib or the liquidation of the institution that acts as Mudarib.
10/2 On the maturity of a Mudarabah operation, the assets should be liquidated in the manner explained in item 8/8.
"""

ijara_rules = """
1. Scope of the Standard
 This standard covers operating leases of properties or Ijarah Muntahia Bittamleek, whether the Institution is the lessor or the lessee.
 This standard does not cover Sukuk al-Ijarah, as they are covered by Shari'ah Standard on Investment Sukuk, nor the employment of persons (labour contract), as it is covered by a separate standard.
2. Promise to Lease (an Asset)
2/1 In principle, an Ijarah contract is executed for an asset owned by the lessor or an usufruct owned by the sub-lessor. However, it is for a customer to request an Institution to acquire the asset or to acquire the usufruct of an existing asset which the customer wishes to take on lease.
2/2 In principle, Ijarah may be effected directly on the asset without any requirement of a preceding master agreement. However, it is permissible to have a master agreement drawn up coveringa number of Ijarah transactions between the Institution and the customer, setting out the general terms and conditions of agreement between the two parties. In this case, there may either be a separate lease contract for each transaction, in a specific written document signed by the two parties, or alternatively the two parties may exchange notices of offer and acceptance by referring to the terms and conditions contained in the master agreement.
2/3 It is permissible for the Institution to require the customer who has promised to lease to pay a sum of money to the Institution to ensure the customer's seriousness in accepting a lease on the asset and the subsequent obligations, provided no amount is to be deducted from 
this sum except in proportion to the actual damage suffered by the Institution in case the customer does not fulfil his promise. Thus, if the customer, in case of Ijarah associated with a promise to transfer ownership, breaches his promise, the promisor shall be charged either the difference between the cost of the asset intended to be leased and the total lease rentals for the asset which is leased on the basis of Ijarah Muntahia Bittamleek to a third party, or, in case of operating Ijarah, the promisor breaching his promise shall be charged the difference between the cost of acquisition and the total selling price if sold to a third party by the Institution (promisee). Otherwise; i.e., in case it is not sold, the promisee shall not be entitled to receive any compensation.
2/4 The amount of money deposited by the customer as security for his commitment can be either held on trust in the custody of the Institution in which case the latter cannot invest it, or it may be held on an investment trust basis in which case the customer permits the Institution to invest it on the basis of Mudarabah between the customer and the Institution. It is permissible to agree with the customer, upon the execution of the contract of lease, that this amount shall be treated as an advance payment of the instalments of the lease rental.
3. Acquisition of the Asset to Be Leased, or Its Usufruct, by the Institution 
3/1 For the permissibility of an Ijarah contract concerning a specified asset, the lease contract should be preceded by acquisition of either the asset to be leased or the usufruct of that asset.
3/1/1 If the asset or the usufruct thereof is owned by the Institution, which should in principle be the case, an Ijarah contract may be executed as soon as agreement is reached by the two parties.
3/1/2 However, if the asset is to be acquired by the customer [see item 3/2 below], or by a third party, the Ijarah contract shall not be executed unless and until the Institution has acquired that asset.
 Ownership is possible under a sale contract, even if the title is not registered in the purchaser's name (the Institution), and the purchaser has the right to obtain a counter-deed to establish the actual transfer of his ownership of the asset. [see item 3/5 below]
3/2 An asset may be acquired by a party and then leased to that party. In this case, the Ijarah transaction should not be stipulated as a condition of the purchase contract by which the Institution acquires the asset.
3/3 A lessee of an asset may enter into a sub-lease contract with a party other than the owner for a rental that is either the same, lower or higher, payable either currently or on a deferred basis, unless the owner stipulates that the lessee should not assign or sublet the property to third parties, or should not do so without his approval.
3/4 The lessee may lease the asset back to its owner in the first lease period for a rental that is lower, same or higher than what he is paying, if the two rentals are paid on a spot basis. However, this is not permissible if it should lead to contract of 'Inah, by varying the rent or the duration. For example, it is not permissible, if the first rental is one hundred dinars payable on a spot basis, for the lessee to sublet it to the lessor for one hundred and ten dinars payable on a deferred basis, or if the first rental is one hundred and ten dinars payable on a deferred basis, for the second to be for one hundred dinars payable instantly, or if the two rentals are of the same amount, but the payment of the first rental is deferred for one month and the second rental is deferred for two months.
3/5 An Ijarah contract may be executed for an asset undertaken by the lessor to be delivered to the lessee according to accurate specifications, even if the asset so described is not owned by the lessor. In this case, an agreement is reached to make the described asset available during the duration of the contract, giving the lessor the opportunity to acquire or to produce it. It is not a requirement of this lease that the rental should be paid in advance as long as the lease is not executed according to the contract of Salam (or Salaf). Should the lessee receive 
an asset that does not conform to the description, then he is entitled to reject it and demand an asset that conforms to the description.
3/6 An Institution's customer may jointly acquire an asset that he wishes to lease with the Institution, and then lease the Institution's share of the asset from the Institution. In this case, the rental specified as receivable by the Institution should only be in proportion to its share in the ownership of the asset, since the lessee is a co-owner of the asset and therefore has to pay rent only on the share that he does not own.
3/7 An Institution may appoint one of its customers to act as its agent in acquiring on its behalf an asset that is desired by that customer such as equipment, machinery, etc., whose description and price are fixed with a view to the Institution's leasing such asset or assets to the customer after it has acquired their ownership through either actual or constructive possession. Although this type of agency (for the purchase of the assets) is permissible, it is always preferred that the agent is someone other than the customer (prospective lessee) as far as possible.
4. Concluding an Ijarah Contract and the Forms of Ijarah4/1 Signature of the contract and the consequences thereof
4/1/1 The lease contract is a binding contract which neither party may terminate or alter without the other's consent [see items 5/2/2, 7/2/1, and 7/2/2]. However, an Ijarah contract may be terminated in accordance with item 7/2/1.
4/1/2 The duration of an Ijarah contract must be specified in the contract. The period of Ijarah should commence on the date of execution of the contract, unless the two parties agree on a specified future commencement date, resulting in a future Ijarah, that is, an Ijarah contract to be executed at a future date.
4/1/3 If the lessor fails to deliver the asset to the lessee on the date specified in the Ijarah contract, no rental is due for the period between the date specified in the contract and the date of actual delivery, and the rental should be reduced accordingly, unless it is agreed that the lease be extended by an equivalent period after its original expiry date.
4/1/4 'Arboun (Earnest Money) may be taken in respect of lease at the execution of the contract of lease, with the lessee having the right to terminate the contract during a specified period of time, and 'Arboun is treated as an advance payment of the rental. If the Ijarah contract is not executed for a reason attributable to the lessee, the lessor may retain the 'Arboun. However, it is preferable for the Institution to forgo any amount in excess of the actual damage it has suffered. [see para. 3/2]
4/2 Forms of the Ijarah contract
4/2/1 Ijarah contracts may be executed in respect of the same asset for different periods for several lessees, provided that two contracts are not executed in respect of the same asset for the same period. Such an arrangement is called "successive leases", because each Ijarah is considered as being successive to the previous one and not concurrent with it on the basis of its being a future Ijarah. [see item 4/1/2 above]
4/2/2 If the lessor signs an Ijarah contract for a particular asset for a specified period of time, he cannot sign another Ijarah contract with another lessee for the duration of the existing Ijarah period or for any remaining period thereof. [see item 7/1/2 below]
4/2/3 An Ijarah contract may be signed with several lessees being entitled to the same specified usufruct of a particular asset and duration of rent, without specifying a particular period of time for a particular person. In this case, each lessee may benefit from the property during the time assigned to him in accordance with specified rules. This case is one form of Muhaya`ah (time-sharing) in benefiting from the usufruct.
4/2/4 A lessee may invite others to share with him in the usufruct he owns. In this case, they become co-owners in the usufruct of the leased property. This can only be done before entering into a sub-lease. If the property is sub-leased after the co-owners having owned the usufruct each co-owner is entitled to a share in the sub-lease rental pro rata to his share in the usufruct.
5. Subject Matter of Ijarah5/1 Rules governing benefit and leased property
5/1/1 The leased asset must be capable of being used while preserving the asset, and the benefit from an Ijarah must be permissible by Shari'ah. For example, a house or a chattel may not be leased for the purpose of an impermissible act by the lessee, such as leasing premises to be used as headquarters by an Institution dealing in interest or to a shopkeeper for selling or storing prohibited goods, or leasing a vehicle to transport prohibited merchandise.
5/1/2 The subject matter of Ijarah may be a share in an undivided asset held in common with the lessee, whether the lessee is a partner with the lessor or not. In this case the lessee may benefit from the leased share in the same way in which the lessor used to benefit from it, i.e., by usufruct division based on Muhaya'ah i.e. by identifying a particular time (time-sharing) or a particular part of the property, used alternately by the coowners, or any other means with consent of the other partner.
5/1/3 An Ijarah contract may be executed for a house or a chattel, even with a non-Muslim, if the use to be made of it is permissible, such as a house for residential purposes, a car for transport, or a computer to store data, unless the lessor knows in advance, or has reason to presume, that the use of the asset to be leased will be for an impermissible purpose.
5/1/4 The lessee must use the leased asset in a suitable manner or in conformity with common practice, and comply with conditions which are acceptable in Shari'ah. He must also avoid causing damage to the leased asset by misuse through misconduct or negligence.
5/1/5 The lessor must accept responsibility for any defects of the leased asset which impair the intended use of the asset, and may not exclude his liability for any impairment that the leased asset may sustain, either by his own doing or as a result of events outside his control, which affect the benefits intended to be available under the Ijarah contract.
5/1/6 If the benefit from the leased asset is impaired wholly or partially as a result of the lessee's misconduct, while the property remains under lease, the lessee is obliged to restore or repair the usufruct, and rent for the time during which the benefit is lost is not to be waived.
5/1/7 The lessor may not stipulate that the lessee will undertake the major maintenance of the asset that is required to keep it in the condition necessary to provide the contractual benefits under the lease. The lessor may delegate to the lessee the task of carrying out such maintenance at the lessor's cost. The lessee should carry out operating or periodical (ordinary) maintenance.
   5/1/8 The leased asset is the responsibility of the lessor throughout the duration of the Ijarah, unless the lessee commits misconduct or negligence. The lessor may take out permissible insurance on it whenever possible, and such insurance expenses must be borne by the lessor. The lessor may take this into account implicitly when the lease rental is to be fixed. However, he may not, after the contract is signed, charge the lessee any cost in excess of the cost anticipated at the time of fixing the rent. The lessor may also delegate to the lessee the task of taking out insurance at the lessor's expense. 5/2 Rules governing lease rentals
5/2/1 The lease rental may be in cash or in kind (goods) or benefit (service). The rental must be specified, either as a lump sum covering the duration of the Ijarah contract, or by instalments for parts of the duration. It may also be for a fixed or variable amount, according to whatever designated method the two parties agree upon. [see item 5/2/3 below]
5/2/2 The rental is made obligatory by the contract and the lessor's entitlement to the rental runs from the time when the lessee starts to benefit from the asset or once the lessor makes the usufruct of the asset available to the lessee, and the entitlement to the rental does not necessarily commence on the date of signing the Ijarah contract. The rental may be paid entirely in advance or in instalments during a period equivalent, or more or less, to the duration of the Ijarah. However, if the asset is made available only after a period longer than what customary practices deem proper, then no payment shall be obligatory.
5/2/3 In case the rental is subject to changes (floating rental), it is necessary that the amount of the rental of the first period of the Ijarah contract be specified in lump sum. It is then permissible that the rentals for subsequent periods be determined according to a certain benchmark. Such benchmark must be based on a clear formula which is not subject to dispute, because it becomes the determining factor for the rentals of the remaining periods. This benchmark should be subject to a ceiling, on both maximum and minimum levels.
5/2/4 It may be agreed that the rental should consist of two specified parts: one to be paid or transferred to the lessor and the other to be held by the lessee to cover any expenses or costs approved by the lessor, such as the cost of major maintenance, insurance, etc. The excess of the second part of the rental shall be treated as an advance to the lessor on account, while the lessor shall bear any shortage.
5/2/5 The amendment of future rentals is permissible by the agreement of both parties, i.e. the periods for which the lessee has not yet received any benefit. The rentals of any previous periods which 
have not yet been paid become a debt owed to the lessor by the lessee, and therefore cannot be increased.
6. Guarantees and Treatment of Ijarah Receivables
6/1 Permissible security, of all kinds, may be taken to secure the rental payments or as a security against misuse or negligence on the part of the lessee, such as a charge over assets, guarantees or an assignment of rights over assets of the lessee held by third parties, even if such rights are a permissible life or property insurance indemnity in favour of the lessee.
6/2 The two parties may agree that the rental be paid fully in advance. It is also permissible to make the rent payable in instalments, in which case the lessor may stipulate that the lessee should immediately pay the remaining instalments if he, after receiving a specified period of due notice, delays, without a valid reason, payment of one instalment or more, provided that the asset shall be made available for the lessee to use for the remaining period of time. Any stipulated upfront rental or accelerated -because of delay of payment- rental is subject to settlement at the end of the Ijarah period or, if the Ijarah contract is terminated earlier, at the time of such termination. Any extension of time by the lessor after the stipulated time for prompt payment is considered as a consent to deferral of payment throughout the extension period and not a right of the lessee, subject always to item 5/2/2 above.
6/3 No increase in the rental due may be stipulated by the lessor in case of delay in payment by the lessee.
6/4 It may be provided in the contract of Ijarah or Ijarah Muntahia Bittamleek that a lessee who delays payment for no good reason undertakes to donate a certain amount or percentage of the rental due in case of late payment. Such donation should be paid to charitable causes under the co-ordination of the Institution's Shari'ah Supervisory Board.
6/5 In case of foreclosure of the security provided by the lessee, the lessor may deduct from such amounts only what is due in respect 
of rental for previous periods, and not all rental instalments, including instalments which have not yet fallen due and in respect of periods for which the lessee has not had the benefit of the leased asset. The lessor may also deduct from the security all legitimate compensations necessitated by the lessee's breach of contract.
7. Changes to the Ijarah Contract7/1 Selling of or damage to the leased asset
7/1/1 If the lessor sells the leased asset to the lessee, the Ijarah contract is terminated due to the transfer of the ownership of the leased asset and ownership of usufruct to the lessee.
7/1/2 The lessor may sell the leased asset to a third party other than the lessee, and the title to the asset together with the rights and obligations of the lessor under the Ijarah contract is thereby transferred to the new owner, because the asset and the rights and obligations attached to it become the right of the third party. The lessee's consent is not necessary when the lessor decides to sell the asset to a third party. If the purchaser does not know about the Ijarah contract, he may terminate the sale contract, but if he knows about it and consents to it, he takes the place of the previous owner in his entitlement to the rental for the remaining period.
7/1/3 In case of total destruction of the leased asset, the Ijarah contract is terminated if it is concluded on an identified asset. In such a case, it may not be stipulated that the rest of the instalments should be paid.
7/1/4 The leased asset in the possession of the lessee is held by the lessee in a fiduciary capacity on behalf of the lessor. The lessee will not be held liable for any damage or destruction of the leased asset unless such damage or destruction is a result of misconduct or negligence on the part of the lessee. In this case, he is obliged to replace the asset if it is replaceable; otherwise, he is liable for the amount of the damage to be determined by valuation.
7/1/5 In case of the partial destruction of the leased asset in a manner that impairs the benefits expected from the leased asset, the lessee may terminate the Ijarah contract. Both he and the lessor may also agree to amend the rental in case of partial destruction of the leased property, if the lessee waives his right to termination. The lessor in this case is not entitled to rent for the period during which the lessee was not able to benefit from the asset unless the lessor makes it up (by agreement with the lessee) with a like benefit after the expiry of the period specified in the contract. [see para. 5/1/6]
7/1/6 In an Ijarah Mawsufah fi al-Dhimmah (contract for an unidentified asset undertaken by the lessor to be delivered according to the agreed specifications), the owner in cases of total and partial destruction must offer an alternative asset having a specification similar to that of the destroyed asset, unless otherwise agreed at the time. The Ijarah shall continue for the remaining time of the contract. If it is not possible to provide a substitute asset, the contract will be terminated. [see item 3/5]
7/1/7 If the lessee stops using the leased asset or returns it to the owner without the owner's consent, the rental will continue to be due in respect of the remaining period of the Ijarah, and the lessor may not lease the property to another lessee for this period, but must keep it at the disposal of the current lessee unless the lessee relinquishes to the lessor the remaining period of time, in which case the lease expires. [see item 7/2/1 below]
7/2 Termination, expiry and renewal of the Ijarah contract
7/2/1 It is permissible to terminate the lease contract by mutual consent but it is not permissible for one party to terminate it except in case of force majeure or there is a defect in the leased asset that materially impairs its use. Termination is also possible when one party secures an option to terminate the contract in which case the party who holds the option may exercise it during the specified period.
7/2/2 The lessor may stipulate that the Ijarah contract be terminated if the lessee does not pay the rent or fails to pay it on time.
7/2/3 An Ijarah contract does not terminate with the death of either party thereto. However, the heirs of the lessee may terminate the Ijarah contract if they can prove that the contract has become, as a result of the death of their legator, too onerous for their resources and in excess of their needs.
7/2/4 An Ijarah contract expires with the total destruction of the leased asset in the case of leasing a specific asset or with the inability to enjoy the usufruct owing to the loss of the benefit that the asset was intended to provide.
7/2/5 The two parties may terminate the Ijarah contract before it begins to run.
7/2/6 The lease expires upon the expiry of its term, but it may remain operative for a good cause, such as the late arrival to the place intended in the lease of transportation vehicles, and in the case of a late harvesting period for land leased for crop cultivation. The lease then continues with the rental based on the prevailing market value. An Ijarah may be renewed for another term, and such renewal may be made before the expiry of the original term or automatically by adding a provision in the new contract for such renewal when the new term starts, unless either party serves a notice on the other of its desire not to renew the contract.
8. Transfer of the Ownership in the Leased Property in Ijarah Muntahia Bittamleek
8/1 In Ijarah Muntahia Bittamleek, the method of transferring the title in the leased asset to the lessee must be evidenced in a document separate from the Ijarah contract document, using one of the following methods:
a) By means of a promise to sell for a token or other consideration, or by accelerating the payment of the remaining amount of rental, or by paying the market value of the leased property.
b) A promise to give it as a gift (for no consideration).
c) A promise to give it as a gift, contingent upon the payment of the remaining instalments.
 In all these cases, the separate document evidencing a promise of gift, promise of sale or a promise of gift contingent on a particular event, should be independent of the contract of Ijarah Muntahia Bittamleek and cannot be taken as an integral part of the contract of Ijarah.
8/2 A promise to transfer the ownership by way of one of the methods specified in item 8/1 above is a binding promise by the lessor. However, a binding promise is binding on one party only, while the other party must have the option not to proceed. This is to avoid a bilateral promise by the two parties which is Shari'ah impermissible because it resembles a concluded contract.
8/3 In all cases of transfer of ownership by way of gift or sale, it is necessary, when the promise is fulfilled, that a new contract be drawn up, since the ownership to the property is not automatically transferred by virtue of the original promise document that was drawn up earlier.
8/4 In case the Ijarah contract is combined, through a separate document, with a gift contingent upon the condition that the remaining rent instalments be paid, the ownership to the leased property is transferred to the lessee if the condition is fulfilled, without the need for any other procedure to be adopted or a document to be signed. However, if the lessee's payment is short of even one instalment, the ownership to the property is not transferred to him, since the condition has not been fulfilled.
8/5 If the leased asset was purchased from the lessee before it was leased back to the lessee on the basis of Ijarah Muntahia Bittamleek, a (reasonable) period of time, between the lease contract and the time of the sale of the asset to the lessee, must have expired, to avoid the contract of 'Inah. This period must be long enough so that the leased property or its value could have changed. This shall 
also apply to the case of early ownership of the asset where a sale contract is concluded during the Ijarah. [see para. 7/1]
8/6 Subject to item 8/8 below, the rules governing Ijarah must apply to the Ijarah Muntahia Bittamleek, i.e. when a promise is made by the lessor to transfer the ownership in the leased asset to the lessee. None of these rules should be breached under the pretext that the leased asset was bought by the lessor on the basis of a promise by the lessee that he would acquire it or that ownership of it would devolve upon him, or that he would pay rentals in excess of those payable in respect of a similar property which are similar in amount to the instalments of an instalment sale, or that local laws and conventional banking practices consider such a transaction as an instalment sale with a deferred transfer of the ownership.
8/7 Transfer of the ownership in the leased property cannot be made by executing, along with the Ijarah, a sale contract that will become effective on a future date.
8/8 If the leased asset is destroyed or if the continuity of the lease contract becomes impossible up to the expiry period without the cause being attributable to the lessee in either case, then the rental is adjusted based on the prevailing market value. That is, the difference between the prevailing rate of rental and the rental specified in the contract must be refunded to the lessee if the latter rental is higher than the former. This is to avoid loss to the lessee, who agreed to a higher rental payment compared to the prevailing rate of rental in consideration of the lessor's promise to pass the title to him upon the expiry of the lease term.
"""

credit_debit_rules = """
1. Scope of the Standard
 The standard covers debit cards, charge cards and credit cards that are issued by Institutions to their customers to enable the latter, by using the cards, either to withdraw cash from their accounts or to obtain credit or to pay for goods or services purchased. These cards include the following types:
• Debit card
• Charge card
• Credit card
2. Characteristics of Different Types of Card
 	While some of the characteristics are common to more than one type of card, some are specific to a particular type of card.
2/1 Characteristics of the debit card
2/1/1 The Institution issues the card to a customer with available funds in his account.
2/1/2 The card confers on its holder the right to withdraw cash from his account or to pay for goods or services purchased up to the limit of the available funds (credit balance) on his account. The debit to the customer's account will be immediate, and the card does not provide him with any credit.
2/1/3 The customer will not normally pay any charges for using this card, except when it is used to withdraw cash or to purchase another currency through another Institution different from the Institution that has issued the card.
2/1/4 The issuing Institution may charge a fee for issuing the card, or may make no charge for issuing it.
2/1/5 Some Institutions charge the party accepting payment by means of the card a commission calculated as a percentage of such payments.
2/2 Characteristics of the charge card
2/2/1 The card provides a credit facility up to certain ceiling for a specified period of time, as well as providing a means of repayment.
2/2/2 The card is used to pay for goods and services and to obtain cash.
2/2/3 This card does not provide revolving credit facilities to the cardholder, insofar as the cardholder is obliged to make payment for the purchased goods or services by the end of a prescribed credit period following receipt of a statement sent by the Institution issuing the card.
2/2/4 If the cardholder delays payment of the amount due beyond the period of free credit, an interest charge is imposed on the cardholder but none is imposed by the Institutions.
2/2/5 The Institution issuing the card does not charge the cardholder any percentage commission on purchases, but receives a percentage commission from the party accepting the card on purchases made by using the card.
2/2/6 The Institution issuing the card is obliged to pay the party accepting the card for purchases made by the cardholder, within a specified transaction credit limit (or the agreed increase thereon). This obligation on the card issuer to pay for the cardholder's purchases is direct, and is independent of the relationship between the party accepting the card and the cardholder.
2/2/7 The Institution issuing the card has a personal and direct right against the cardholder to be reimbursed for any payments made on his behalf. The issuer's right is absolute and independent of 
the relationship between the cardholder and the party accepting the card in accordance with the contract between them.
2/3 Characteristics of the credit card
2/3/1 This card provides a revolving credit facility within the credit limit and credit period determined by the issuer of the card. It is also a means of payment.
2/3/2 The holder of a credit card is able to pay for purchases of goods and services and to withdraw cash, within the approved credit limit.
2/3/3 When purchasing goods or services, the cardholder is given a free credit period during which the amount due should be paid and no interest is chargeable. The cardholder is also allowed to defer paying the amount due and is charged interest for the duration of the credit. In the case of a cash withdrawal, there is no free credit period.
2/3/4 The conditions set out in items 2/2 (e), (f) and (g) above are equally applicable to this type of card.
3. Shari'ah Rulings for Different Types of Card3/1 Debit card
 It is permissible for Institutions to issue debit cards, as long as the cardholder does not exceed the balance available on his account and no interest charge arises out of the transaction.
3/2 Charge card
 	It is permissible for Institutions to issue charge cards on the following conditions:
3/2/1 The cardholder is not obliged to pay interest in the case of delay in paying the amount due.
3/2/2 If the Institution obliges the cardholder to deposit a sum of money as a guarantee and this amount is not available for the use of the card holder, then it must be made clear that the Institution will invest the money for the benefit of the cardholder on the basis of Mudarabah and that any profit accruing on this amount will be shared between the cardholder and the Institution according to a specified percentage.
3/2/3 The Institution must stipulate that the cardholder may not use the card for purposes prohibited by the Shari'ah and that the Institution has the right to withdraw the card in case such a condition is violated.
3/3 Credit card
 It is not permissible for an Institution to issue credit cards that provide an interest-bearing revolving credit facility, whereby the cardholder pays interest for being allowed to pay off the debt in instalments.
4. General Provisions4/1 The affiliation of the Institution to membership of international card regulatory organizations
4/1/1 It is permissible for Institutions to join the membership of international card regulatory organizations, provided the Institutions avoid any infringements of Shari'ah that may be prescribed by those organizations.
4/1/2 It is permissible for the Institutions to pay membership fees, service charges and other fees to international card regulatory organizations, so long as these do not include interest payments, even in an indirect way, such as in the case of increasing the service charge to cater for the granted credit.
4/2 Commission to the card issuer payable by merchants accepting the card
 It is permissible for the Institution issuing the card to charge a commission to the party accepting the card, at a percentage of the purchase price of the items and services purchased using the card.
4/3 Fees charged by the Institution to the cardholder
 It is permissible for the Institution issuing the card to charge the cardholder membership fees, renewal fees and replacement fees.
4/4 Purchasing gold, silver and currency with cards
 It is permissible to purchase gold, silver or currency with a debit card or a charge card, in cases where the issuing Institution is able to settle the amount due to the party accepting the card without any delay.
4/5 Cash withdrawal using a card
4/5/1 It is permissible for the cardholder to withdraw an amount of cash within the limit of his available funds, or more with the agreement of the Institution issuing the card, provided no interest is charged.
4/5/2 It is permissible for the Institution issuing the card to charge a flat service fee for cash withdrawal, proportionate to the service offered, but not a fee that varies with the amount withdrawn.
4/6 Privileges granted by card issuing parties
4/6/1 It is not permissible for Institutions to grant the cardholder privileges prohibited by the Shari'ah, such as conventional life insurance, entrance to prohibited places or prohibited gifts.
4/6/2 It is permissible to grant privileges to the cardholder that are not prohibited by the Shari'ah, such as a priority right to services or discounts on hotel, airline or restaurant reservations and the like.
"""